name: continuous_background_worker
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  rxdart: ^0.28.0
  flutter_background_service: ^5.0.6
  async: ^2.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
